apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path   : "argoCD/HelmCharts/app"
    repoURL: "git@github.com:egorvit/Devops.git"
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true