# Dev Override Values for apache Helm Chart

replicaCount: 1

image:
  repository: httpd
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

apacheConfig:
  customConfig: |
    # Указываем, какой модуль загружать
    LoadModule dir_module modules/mod_dir.so

    ServerRoot "/etc/httpd"
    Listen 80

    ServerName localhost:80

    DocumentRoot "/var/www/html"

    <Directory "/var/www/html">
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>

    ErrorLog "logs/error_log"
    CustomLog "logs/access_log" common

    TypesConfig /etc/mime.types

    <Directory "/var/www/html">
        AllowOverride All
    </Directory>

    <IfModule mod_ssl.c>
        SSLProtocol all -SSLv2 -SSLv3
    </IfModule>

indexPage: |
  <html>
    <head><title>Welcome to Dev stand!</title></head>
    <body><h1>Hello, World!</h1></body>
  </html>

