version: '3'
services:
  kafka-ui:
    image: provectuslabs/kafka-ui:f124fa632d10aaad7d79c9ee0b00f32922079972
    container_name: kafka-ui
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=172.21.40.7:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER_CONNECT=172.21.40.7:2181
    restart: always
