apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "Chart.fullname" . }}-config
data:
  nginx.conf: {{ .Values.config.nginx.conf | quote }}
  index.html: {{ .Values.customIndexPage | quote }}